CREATE TABLE IF NOT EXISTS "phones" ([id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
[url] VARCHAR(500) NOT NULL,
[brand] VARCHAR(60) NOT NULL,
[model] VARCHAR(60) NOT NULL,
[screensize] INTEGER NOT NULL,
[os] VARCHAR(60) NOT NULL);

